### ISSUE TITLE
PPPwn not running

### ISSUE THREAD

**Issue by sauyadav** [0x1iii1ii/PPPwn-Luckfox#105]
I have installed 1.2.5 version and auto run is enabled but it is still not running at the boot.

**Comment by ps4user1238** [comment]
configure the "auto run PPPwn on Start-up at 192.168.1.1 type the ip address in on your browser then "run pppwn"

**Comment by turbletone** [comment]
Hi, same problem over here. New installation of 1.2.5 via MobaXterm. I deleted all files from 1.2.4, copy new files from 1.2.5 version, install with script.

I start ps4 pro and it doesn't run pppwn automatically unless I log into the web server and press the ‘run pppwn’ button. I have checked ‘Auto-Run PPPwn on Start-Up’ in the settings, but it doesn't work when I start ps4 from scratch.

**Comment by ps4user1238** [comment]
you should see the prompt cannot connect to network on start-up wait a minute before configuring it via website again as sometimes it can take time for the message prompt to pop up does your playstation freeze for a second when accessing the browser at the start, if so that means that the pppwn script is running

**Comment by ps4user1238** [comment]
also make sure everytime you shutdown the ps4 either take the wire out or switch the plug out as the luckfox pico needs the playstation to be completley off to refresh the jailbreak process its a pain in the ass but its the only way the auto jailbreak feature works

**Comment by turbletone** [comment]
I have installed the prebuild image for 9.00 and now it works on boot after modifying the Auto-Run option in the configuration. There must be something wrong with my luckfox installation. Thanks for your help!

**Comment by 0x1iii1ii** [comment]
I'll build another image with auto-start enabled by default and without the web server.

**Comment by 0x1iii1ii** [comment]
check out the latest update release!

**Comment by sauyadav** [comment]
It is working, Thank you!
