### ISSUE TITLE
No update.img in latest buildroot (1.2.5)

### ISSUE THREAD

**Issue by PoliPyc** [0x1iii1ii/PPPwn-Luckfox#107]
Hi, I use upgrade_tool (no windows machine) to update my luckfox pico plus.
I noticed that latest image pack does not contain update.img which I need to upgrade device.
I would be grateful if you could include this file. At least for pico plus fw 11.00 be it with web server or not :)

Thank you for your hard work!

**Comment by 0x1iii1ii** [comment]
i remove it to save file size, will add it back for ur fw 11.00

**Comment by Zidar05** [comment]
А как обновлять через upgrade_tool?
And how to update via upgrade_tool ?

**Comment by PoliPyc** [comment]
Awesome! Works as expected. Thanks!
