### ISSUE TITLE
Download rootfs fail

### ISSUE THREAD

**Issue by al10capote** [0x1iii1ii/PPPwn-Luckfox#112]
When i trybto flash the 9.0 to 11.0 web server imagen don't ending the procesos,put download rootfs fail voz partition ending is more larger than flash size

**Comment by AceCuba** [comment]
same issue here

**Comment by 0x1iii1ii** [comment]
List your Luckfox models, the pre-build you downloaded, screenshots, etc., so I can help. I have no idea what causes the problem if you don't provide additional details.
