### ISSUE TITLE
Question: 9.60 with Luckfox Pico Pro - Goldhen update

### ISSUE THREAD

**Issue by KXRIST** [0x1iii1ii/PPPwn-Luckfox#117]
I would like to knwo how is it possible to update goldhen. If i put usb with the updated goldhen i get shutdown.

Do i have to enter through ftp to delete previous and update or this has to be done with the usb again ? if so what is the version i should go for to avoid any problem ?

**Comment by 0x1iii1ii** [comment]
this version has no stage2 update, you just need to put the new golden on the USB to update.

**Comment by KXRIST** [comment]
Worked, thanks!
