### ISSUE TITLE
Using ps4 to PoE (power over ethernet) the luckfox

### ISSUE THREAD

**Issue by crijopoga** [0x1iii1ii/PPPwn-Luckfox#12]
Could be possible to extract 5v from the internal ps4 and wire it to a pin from the Ethernet port (using PoE pin out) , solder a wire from the power input from the luckfox to the same pin on its ethernet port ? So it can be feeded that way eliminating the USB cable and not affecting using Ethernet normally after activating golden?

**Comment by 0x1iii1ii** [comment]
you can't, PS4 won't support PoE. If it does you still need to step down the voltage.

**Comment by neburone10** [comment]
Hello, I have carried out this chip integration: https://www.reddit.com/r/ps4homebrew/comments/1df9a6y/integrated_luckfox_autojailbreak_on_ps4_pro/ and here is a small tutorial https://neburone10.github.io/
