### ISSUE TITLE
Password won't work for me. How can I troubleshoot?

### ISSUE THREAD

**Issue by Ayala** [0x1iii1ii/PPPwn-Luckfox#14]
Purchased a Luckfox Pico Max RV1106, followed the steps several times using the 1106 chip selection and copied all except the update image. All works as instructed until I have to enter the "luckfox" password to ssh in and I'm denied access.

I've tried several times with different cards and I can't get through.

thanks in advance for any assistance.

**Comment by 0x1iii1ii** [comment]
are you sure you burn the OS right? try to use 
``Login: root, Password: luckfox``
If you can log in, that's means your SD has a problem or you made a mistake when burning the OS.

**Comment by Jstzo2u** [comment]
Login name: ”root“ or ”pico“, password: Luckfox

**Comment by Ayala** [comment]
> are you sure you burn the OS right? try to use `Login: root, Password: luckfox` If you can log in, that's means your SD has a problem or you made a mistake when burning the OS.

Yeah I've created it multiple times on two separate cards and I've tried both root and pico as user. I'm waiting for another card since I suppose both my sd cards could be bad (unlikely, but trying to eliminate points of error).

**Comment by Ayala** [comment]
5th time was the charm... I went through 5 SD cards ultimately the 5th card seemed to do the trick, a 64gb sandisk card. I didn't think I'd have to go up this high in capacity but he other cars weren't taking.
