### ISSUE TITLE
9.03fw - "LAN not Connected"

### ISSUE THREAD

**Issue by ba114** [0x1iii1ii/PPPwn-Luckfox#15]
Firware: 9.03
PS4 Model: PS4 Pro
HW: Luckfox Pico Pro 128mb
Image: Luckfox_Pico_Pro_Max_Ubuntu_SDCard
SD Card: 8gb

Issue: Jailbreak is never successful and eventually results in a message displaying "LAN not connected", Following this error, the lights on the luckfox device no longer flash.

Symptons leading to issue: Monitoring the system information page, upon each time re-obtaining the 42.42.42.42 IP address, after approximately 5-6 seconds there is a pause/stutter in the dashboard sound output followed by dropping the IP address.
The ps4 obtains and loses the 42.42.42.42 IP address up to 6 times before the issue is encountered. 

I have tried two different usb drives with goldhen and neither have given a different outcome.

**Comment by 0x1iii1ii** [comment]
9.03 is a vtx hen, it's pointless to try with goldhen payload. you can update your ps4 to 9.60 to get goldhen support and try again. soon I'll remove vtx hen from version 9.03, 10.50 and 10.70.

**Comment by ba114** [comment]
Ok so if i use stage 1.bin and stage 2.bin files for HEN-VTX along with the VTX-HEN.bin payload it would work?
