### ISSUE TITLE
Refusing to reload, not enough space available

### ISSUE THREAD

**Issue by angomania** [0x1iii1ii/PPPwn-Luckfox#17]
Installed today PPPwn-Luckfox (Luckfox Pico Plus) on a 16 GB SD.

After running the commands:
git clone https://github.com/0x1iii1ii/PPPwn-Luckfox.git
cd PPPwn-Luckfox
chmod +x install.sh
sudo ./install.sh

 I was asked which FW I want to run. I have selected 9.00. Then I got the following error message:

You have selected firmware version 900. Is this correct? (y/n)
Enter your choice: y
Created symlink /etc/systemd/system/multi-user.target.wants/pppwn.service → /etc/systemd/system/pppwn.service.
Failed to reload daemon: Refusing to reload, not enough space available on /run/systemd. Currently, 6.0M are free, but a safety buffer of 16.0M is enforced.
install completed! rebooting...

After the reboot Luckyfox no longer starts. 
I have to reinstall but I keep getting stuck at the same point.

**Comment by angomania** [comment]
It works ;)

I thought I had done something wrong because I could no longer access with putty.
Thank you.

**Comment by Telscrt** [comment]
Mine isn't seeing IP address on the ps4
