### ISSUE TITLE
Update to new version after installing old version

### ISSUE THREAD

**Issue by xMonTersx** [0x1iii1ii/PPPwn-Luckfox#18]
I successfully installed the previous version 1.0.0. Now, I want to update to version 1.0.2. Should I follow the same installation process again?

**Comment by 0x1iii1ii** [comment]
log in to your luckfox, connect it to internet, paste this cmd, and setup again: 

```sh
cd PPPwn-Luckfox
git pull
chmod +x install.sh
sudo ./install.sh
```

**Comment by xMonTersx** [comment]
Thank you!

**Comment by andregrillo** [comment]
Hope this can help someone trying to update...

I encountered an issue when trying to update, there was not enough free space in `/run` when trying to reload the systemd daemon:
```Failed to reload daemon: Refusing to reload, not enough space available on /run/systemd. Currently, 6.0M are free, but a safety buffer of 16.0M is enforced.```

To resolve this, I remounted `/run` with a larger size before running the install.sh script, which worked perfectly. Here are the steps I followed:

1. **Check the current size and usage of `/run`**:

    ```bash
    df -h /run
    ```

    Example output:

    ```
    Filesystem      Size  Used Avail Use% Mounted on
    tmpfs           6.8M  664K  6.1M  10% /run
    ```

2. **Remount `/run` with a larger size (e.g., 32MB)**:

    ```bash
    sudo mount -o remount,size=32M /run
    ```

3. **Verify the new size**:

    ```bash
    df -h /run
    ```

    Example output after remounting:

    ```
    Filesystem      Size  Used Avail Use% Mounted on
    tmpfs           32M   664K   31M   2% /run
    ```

By increasing the size of `/run`, I was able to successfully finish the install.sh with no errors. 
I hope this helps anyone else facing the same issue!

**Comment by 0x1iii1ii** [comment]
thanks @andregrillo for the quick tuts on the error! we can just ignore that error since it didn't affect the jailbreak process, mostly this happened on Plus/Mini models due to the small RAM size. but I'll appreciate your solution and will add it to the install.sh later to avoid more questions.
