### ISSUE TITLE
time difrrence in models

### ISSUE THREAD

**Issue by narhamraatallah** [0x1iii1ii/PPPwn-Luckfox#2]
does pico pro  , max 128mb,264mb , plus 64mb memory has diffrent time to pppawn ps4 or they all take same time ?

**Comment by 0x1iii1ii** [comment]
I only tested 2 boards so far Luckfox Pro and Mini, and both seem the same in terms of executed pppwn, but for the PPPwned time you asking it depends on PS4, sometimes it takes many tries, sometimes only once. so I can't say it all takes the same time. All boards still need to be tested, If you did test all of those feel free to let me know I'll add it to README.

**Comment by darthtrader6502** [comment]
> does pico pro , max 128mb,264mb , plus 64mb memory has diffrent time to pppawn ps4 or they all take same time ?

i am doing same testing now...gonna try pro later...any update or finding?
