### ISSUE TITLE
Luckfox off

### ISSUE THREAD

**Issue by Paskale84** [0x1iii1ii/PPPwn-Luckfox#20]
Is possible After hack, shutdown the device in automatic script ? I have modified a stage 2 for Linux start and in booting crash my Linux distribution

**Comment by 0x1iii1ii** [comment]
before you open this issue, have you tested the device yet? did you not see it shut down? 
That feature has already been added for a while now, go and check your luckfox red LED after it cracked, to see if it turns on or off.
