### ISSUE TITLE
PS4 Shuts Off After PPPwnd message

### ISSUE THREAD

**Issue by authrequest** [0x1iii1ii/PPPwn-Luckfox#21]
My PS4 9.00 shutsdown after the PPPwnd message and when I restart it it goes into the checking hdd. So not sure what is happening there. I have a USB stick with goldhen.bin formatted as exFAT.

**Comment by 0x1iii1ii** [comment]
is it always happening or once in a while? if once in a while, it's normal because you're trying to jailbreak it. just try again.

**Comment by authrequest** [comment]
It has happened everytime I do it, 3-4 times already. I will keep trying.

**Comment by authrequest** [comment]
Still shutting down...

**Comment by authrequest** [comment]
> Still shutting down...

It is getting stuck on Defeating KASLR

**Comment by 0x1iii1ii** [comment]
did you get the latest update of PPPwn-Luckfox? the recent update fixed some PS4 models that does not support PPPwn, look like your PS4 is one of them. can you try using PC software [PPPwn Lite](https://github.com/PSGO/PPPwn-Lite) to jailbreak it?

**Comment by Doyle4** [comment]
Shutdown the PS4, boot into recovery mode and install 9.00 FULL firmware NOT 9.00 UPDATE.
Sometimes a fresh install helps.

Clear cookies and cache in web browser, although the jailbreak doesn't use the web browser, it does use the network and sometimes cached files can cause issues.

**Comment by ps4rokx** [comment]
Problem is when I try to restart or shutting down PS4.. system goes force off...  Solution pls..

**Comment by Doyle4** [comment]
> Problem is when I try to restart or shutting down PS4.. system goes force off... Solution pls..

Reboot PS4 after hard shut down and then restart PS4 again once it has booted to stock state.
