### ISSUE TITLE
v1.0.3 still shutdown after successful jailbreak

### ISSUE THREAD

**Issue by ssarfaty** [0x1iii1ii/PPPwn-Luckfox#26]
i have tried 1.0.3 configure it not to shutdown after successful jail break but still after jailbreak i'm getting a message that the lan is disconnecting from the device and it doesn't re-initiate the jailbreak after i reset the PS4 v11.0 i have.

let me know if you need anything to help debug this.

**Comment by ZyHead** [comment]
I had the same issue. I restarted the process from zéro, formating the SD card. And now it works great !

**Comment by labba** [comment]
> I had the same issue. I restarted the process from zéro, formating the SD card. And now it works great !
i'm using the Plus model. 
i have done formating twice already and still shutdown

this is from the last screen before runing the install script:
```
You have selected the following settings:
PS4 Firmware: 11.00
PPPwn executable: pppwn
Shutdown after successful jailbreak: no
```

after jailbreak Lan is disconnecting...

**Comment by 0x1iii1ii** [comment]
> after jailbreak Lan is disconnecting...

LAN disconnect does not mean it shutdown, its purpose is to free the Ethernet port after jailbreak if you want to connect your PS4 to the internet. For the shutdown, you can check the red LED on Luckfox if it still blinks, it means the Luckfox is on.

**Comment by ssarfaty** [comment]
after i have rebooted the PS4 , the jailbreak doesn't kick-in again ..
