### ISSUE TITLE
9.0何时能支持啊

### ISSUE THREAD

**Issue by 1987Lr1987** [0x1iii1ii/PPPwn-Luckfox#3]

**Comment by 0x1iii1ii** [comment]
but still welcome if anyone is willing to do it.

**Comment by 1987Lr1987** [comment]
因为esp32和拔插usb断电几率较高，并且需要手动操作，rv1160相当于玩客云袖珍版，破解成功率高，且全自动无需操作，希望大佬能更新支持9.0版本

**Comment by 0x1iii1ii** [comment]
I'll consider it.

**Comment by Doyle4** [comment]
From what I can see, just need to change the command line to 9.00 from 11.00 and swap out the Stage files from 11.00 to 9.00 stage files, and offsets for 9.00.

**Comment by 0x1iii1ii** [comment]
> From what I can see, just need to change the command line to 9.00 from 11.00 and swap out the Stage files from 11.00 to 9.00 stage files, and offsets for 9.00.

yes! You can use that method or wait for me to port all versions with dynamic version selection with only one .sh script. I'm working on it right now...I might update it later today.

**Comment by 506663820** [comment]
Can 9.6 be prefabricated into the program

**Comment by 0x1iii1ii** [comment]
sure, when GoldHEN for 9.60 is released!

**Comment by 1987Lr1987** [comment]
![image](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/122799639/90a6f578-9fee-4e1f-aa2d-454334b1d568)

刷机完成后，第一次用于破解，大约5个轮回完成破解，无断电，感谢大佬🙏

**Comment by 1987Lr1987** [comment]
大佬，ps49.0,破解成功后luckfox面板上的灯还在闪烁，设备并未关机，ps4上还会提示无法连接网络，可能luckfox破解成功后还是会不停的尝试破解

**Comment by 0x1iii1ii** [comment]
No, after it PPPwned, it will no longer try again! the message you see is the last successful attempt. Also, I added a shutdown cmd, it should now shut down the luckfox after successfully jailbreak.
