### ISSUE TITLE
problemas nand

### ISSUE THREAD

**Issue by israel9845** [0x1iii1ii/PPPwn-Luckfox#31]
me gustaria saber si puedo pasar de nand a sd card otra vez, y como hacerlo. ya que con este metodo recibo muchos kernel panics

**Comment by 0x1iii1ii** [comment]
Scroll down, and you'll see the SD installation.

**Comment by israel9845** [comment]
ya hice todo lo que pone abajo pero no me reconoce la tarjeta, gracias

**Comment by israel9845** [comment]
El problema es que con la misma tarjeta que antes funcionaba hice todos los pasos que pone en el repositorio y cuando intento conectarme con la otra IP no me deja . Es como si no estuviera la tarjeta conectada

**Comment by israel9845** [comment]
ya lo solucione amigo, hay que esperar los 5 o 10 minutos a que carge otra vez
