### ISSUE TITLE
Pico plus with NAND method doesn't work

### ISSUE THREAD

**Issue by ssarfaty** [0x1iii1ii/PPPwn-Luckfox#34]
after doing all stages and doing it again after reflashing nand via the Burning SPI NAND Flash Images and retrying again installing v1.1.0 the PS4 doesn't seems to communicate with the Pico Plus device

with the SD everything works just fine, but with the NAND installation (removed the SD) nothing seems to be working in the Lan communication with the PS4

**Comment by Sadiiq1998** [comment]
I have the same problem with luckfox pico pro max with SD card everything works fine but with NAND installation  without SD card it connects for a while then disconnect itself automatically...

**Comment by achm3t** [comment]
Hello. Have same problem with luckfox pico mini b. Both nand and sd methods does not work. PS4 does not obtain any ipa address via LAN. Tested on same ps4 pro with luckfox pro max - both nand and sd methods work like a charm. On pico mini b just no reaction. Funny thing - if I chose “shutdown after success” in install_nand.sh script pico mini b just turns off in about 20-30 seconds after it boots with lan connected or disconnected to console.

**Comment by 0x1iii1ii** [comment]
I don't have pico plus for test atm, so try to flash this image and re-install pppwn again and let me know if it works! 


![Screenshot 2024-07-04 225300](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/73976219/41d27659-48a7-4c9e-8e43-5655b328635d)

**Comment by 0x1iii1ii** [comment]
Also, try to erase NAND first before flashing the buildroot image file.

**Comment by 0x1iii1ii** [comment]
> Hello. Have same problem with luckfox pico mini b. Both nand and sd methods does not work. PS4 does not obtain any ip address via LAN. Tested on same ps4 pro with luckfox pico max - both nand and sd methods **works like a charm**. On pico mini b just **no reaction**. Funny thing - if I chose “shutdown after success” in install_nand.sh script pico mini b just turns off in about 20-30 seconds after it boots with either lan connected or disconnected to console.

try the above solution if it's still not working re-check your wiring.

**Comment by achm3t** [comment]
> I don't have pico plus for test atm, so try to flash this image and re-install pppwn again and let me know if it works!
> 
> ![Screenshot 2024-07-04 225300](https://private-user-images.githubusercontent.com/73976219/345890252-41d27659-48a7-4c9e-8e43-5655b328635d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMTYwNTQsIm5iZiI6MTcyMDExNTc1NCwicGF0aCI6Ii83Mzk3NjIxOS8zNDU4OTAyNTItNDFkMjc2NTktNDhhNy00YzllLThlNDMtNTY1NWIzMjg2MzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE3NTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZGVmMWI3NmIwZTc5MmEyN2Y4NTg3ZGVjNWVmM2RmZGI1MzBkNzdkNjAzYWRkMDMzMWVmMDBjYjlmYTA3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9HGqvkBnhiCiBqWBkFmCNVOnr_hbJnqv50bUI9f_hys)

Ok. I’ll try it. Will be back with info in next 13 hours :)

**Comment by ssarfaty** [comment]
> I don't have pico plus for test atm, so try to flash this image and re-install pppwn again and let me know if it works!
> 
> ![Screenshot 2024-07-04 225300](https://private-user-images.githubusercontent.com/73976219/345890252-41d27659-48a7-4c9e-8e43-5655b328635d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMzk3OTgsIm5iZiI6MTcyMDEzOTQ5OCwicGF0aCI6Ii83Mzk3NjIxOS8zNDU4OTAyNTItNDFkMjc2NTktNDhhNy00YzllLThlNDMtNTY1NWIzMjg2MzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDAwMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMDlmNTZiMzMzZTM4MmI0MTk2MzM1NDJhMTNkNzFkNGQyYWU5ZmE5NWJiMWQ0NWQ5YjE3ZWQ2YmExNWQzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XD9tT_8uGal4GrnhLHuEXeaowKFAyZ-U4mlXnRY4avI)

i have earse and re-write the nand buildroot and nothing helped.

what HW are you using if you don't have the pico plus ?

**Comment by xMonTersx** [comment]
Is NAND method faster than SD? should I switch to NAND method?

**Comment by ssowww** [comment]
Just as a confirmation note:
Did get a brand new **Pico Plus (64MB)** and used the **NAND method successfully** on a **PS4Pro 7216b with FW 9.60**.
Can't tell if it's faster, as no testing with SD on that device was done, but it's definitely not as fast as Pico Max with SD method on PS4Pro 7216b with FW 9.00.
Next testing will be rest mode, although not relevant for me - don't use it on a day2day base.

**Comment by achm3t** [comment]
> > I don't have pico plus for test atm, so try to flash this image and re-install pppwn again and let me know if it works!
> > ![Screenshot 2024-07-04 225300](https://private-user-images.githubusercontent.com/73976219/345890252-41d27659-48a7-4c9e-8e43-5655b328635d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMTYwNTQsIm5iZiI6MTcyMDExNTc1NCwicGF0aCI6Ii83Mzk3NjIxOS8zNDU4OTAyNTItNDFkMjc2NTktNDhhNy00YzllLThlNDMtNTY1NWIzMjg2MzVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDE3NTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZGVmMWI3NmIwZTc5MmEyN2Y4NTg3ZGVjNWVmM2RmZGI1MzBkNzdkNjAzYWRkMDMzMWVmMDBjYjlmYTA3MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9HGqvkBnhiCiBqWBkFmCNVOnr_hbJnqv50bUI9f_hys)
> 
> Ok. I’ll try it. Will be back with info in next 13 hours :)

Guys, please forgive a dumb user. All my issues created by my own! Last time I’ve made a mistake and downloaded mini b firmware from buildroot folder. But it’s clearly written that I should have downloaded “pico plus” one, not “pico mini b”! **0x1iii1ii**, you’ve recommended to use firmware from “backup” folder, but it works with usual pico plus. Again sorry for my inattentiveness, all is working, as it should. Thanks for your great work!
