### ISSUE TITLE
Burning Ubuntu image files installs Buildroot OS

### ISSUE THREAD

**Issue by lapwat** [0x1iii1ii/PPPwn-Luckfox#35]
Following the instructions in the README:

1. Download the ZIP file named `Luckfox_Pico_Plus_Ubuntu_SDCard.zip`
2. Extract it
3. Burn `.img` files except the `update.sh`

Now when I connect over SSH:
- The `pico` user does not exist
- I can only connect with `root` user and `luckfox` password
- `apt`, `bash` and `systemctl` are not installed in the OS
- The OS is NOT Ubuntu, it is Buildroot

```sh
# cat /etc/os-release 
NAME=Buildroot
VERSION=-g68ee52d1d
ID=buildroot
VERSION_ID=2023.02.6
PRETTY_NAME="Buildroot 2023.02.6"
```

Do you have an idea on what is going on ?

**Comment by lapwat** [comment]
It ended up being that the LuckyFox does not boot from the SD Card, it boots from the internal system running `Buildroot`.

**Comment by 0x1iii1ii** [comment]
if you follow the step right, check your sd card, there are many people have problem like you, the solution is try another SD Card.

**Comment by lapwat** [comment]
Thank you for your response. I have used the NAND version ans it works great! Is there an advantage to use the SD Card version over the NAND version ?

**Comment by 0x1iii1ii** [comment]
no, NAND is a better option, just stick to it!
