### ISSUE TITLE
Luckfox pico mini b using Nand IP address Failed 

### ISSUE THREAD

**Issue by Telscrt** [0x1iii1ii/PPPwn-Luckfox#37]
When done with the procedure on the nand section and also the MobaXtem section when plugged to the console the IP address fails please help need solution don't want to use the sscard method on the mini

**Comment by 0x1iii1ii** [comment]
can you provide more detail about your problem? what's really the issues? make sure you burn the buildroot `pico plus image` which i mentioned in step 3.

**Comment by Telscrt** [comment]
Thanks 
Check out my hidden Layout 
![IMG20240713041837](https://github.com/user-attachments/assets/9e5fc9e3-6542-4a96-8941-a7416550edc8)
![IMG20240713053123](https://github.com/user-attachments/assets/adab99d2-4030-4ef1-bb11-797052863d77)
