### ISSUE TITLE
disconection

### ISSUE THREAD

**Issue by fraggola** [0x1iii1ii/PPPwn-Luckfox#40]
HI all, first excuse me for my poor english.My luckfox pico max disconect e few secondes after connection.Do somebody has de same probleme ?
I t would be great if someone could help me.

**Comment by darthtrader6502** [comment]
> HI all, first excuse me for my poor english.My luckfox pico max disconect e few secondes after connection.Do somebody has de same probleme ? I t would be great if someone could help me.

connect to where? when? while setting it on pc?

**Comment by Sadiiq1998** [comment]
> HI all, first excuse me for my poor english.My luckfox pico max disconect e few secondes after connection.Do somebody has de same probleme ?
> 
> I t would be great if someone could help me.
> 
> 

I had the same problem with NAND method only try to factory reset your luckfox to default and reinstall the PPPwn again if that doesn't solve the problem try SD method use micro SD..

**Comment by fraggola** [comment]
Hi, and thank you for the answers.But i do not know how to factory reset the luckfox.Kwowing that i can do nothing when i connect it, because  it disconnect almost straight away :(

**Comment by Sadiiq1998** [comment]
> Hi, and thank you for the answers.But i do not know how to factory reset the luckfox.Kwowing that i can do nothing when i connect it, because  it disconnect almost straight away :(

Contact me on email and i'll show you how to do it here is my email : sadiqmarco11@gmail.com

**Comment by Telscrt** [comment]
Connect your luck fox MAX to SOC toolkit by clicking on the boot button before connecting it to your USB type c then select your select your chIp type for your luck fox MAX then click on advanced settings download bin erase all then re burn the firmware for your device
