### ISSUE TITLE
Linux Payload ?

### ISSUE THREAD

**Issue by darkuser89** [0x1iii1ii/PPPwn-Luckfox#44]
can you add linux payloads?

**Comment by 0x1iii1ii** [comment]
maybe

**Comment by 0x1iii1ii** [comment]
added. Merged from @harsha-0110 https://github.com/0x1iii1ii/PPPwn-Luckfox/pull/49#issue-2458480486

**Comment by 0x1iii1ii** [comment]
@darkuser89 please test to see if it works, thank you.

**Comment by darkuser89** [comment]
I just tested it, Linux starts without problems
