### ISSUE TITLE
Unable to open web interface

### ISSUE THREAD

**Issue by CHENGSHANGFA** [0x1iii1ii/PPPwn-Luckfox#46]
Your idea is great!
I followed the steps and after the installation was completed, when I connected the PS4 console it was automatically jailbroken, I entered the IP address: 192.168.1.1 The connection failed.
My PS4 is version 11.00 and the Luckfox model is Luckfox Pico Plus.
What causes this?
Thank you

**Comment by 0x1iii1ii** [comment]
Make sure to burn the custom image from the release page and answer yes when asking the web server.

**Comment by CHENGSHANGFA** [comment]
Thank you
Downloaded and reinstalled it on the page, connected to PS4 and I saw the IP address: 42.42.42.42 and then it became ‘automatic’. 192.168.1.1 does not appear.
Do you want to use the Web Server features? (y/n)
Enter your choice: y

![1](https://github.com/user-attachments/assets/a6c46a7b-123c-4927-8f85-4111d4bacd5c)
![2](https://github.com/user-attachments/assets/d319aa9a-6b44-4eb6-90a1-bc1fd2a1a3ec)
![3](https://github.com/user-attachments/assets/2b3313c5-ea9c-45c1-b5fe-f007ada863ed)

**Comment by 0x1iii1ii** [comment]
you set up ps4 pppoe settings wrong, user name and password should be `ppp`

![Screenshot 2024-08-09 163907](https://github.com/user-attachments/assets/aa23fc46-2b84-42ea-b4b8-dd5d47f897a8)

**Comment by CHENGSHANGFA** [comment]
Thank you!
User name and password set ppp.
It worked!
Thank you for all your assistance

**Comment by Doyle4** [comment]
Weird, Im having same issue, but all settings are correct, 192.168.1.1 isn't working.

Network shows: 
IP address settings PPPoE
User ppp
password ppp
IP/subnet/default gateway/primary dns/second dns/ AUTOMATIC

I can't access the web server

**Comment by harsha-0110** [comment]
Make sure to use image given in the repo and web server won't be accessible while pppwn is running.

**Comment by Doyle4** [comment]
If anyone knows how to stop SFTP error that be great, some reason it constantly fails uploading the oem file.
