### ISSUE TITLE
Request for the config file.

### ISSUE THREAD

**Issue by lakshmihon29** [0x1iii1ii/PPPwn-Luckfox#47]
Can you please provide the configuration file that is used to build the custom buildroot for pppwn, it'll be help for me to customize my luckfox pico.

**Comment by 0x1iii1ii** [comment]
I didn't save the config file tho and already cleaned the build, but how are you planning to customize it? anything special from my build?

**Comment by lakshmihon29** [comment]
I just want to increase the ram, BTW can you please list the options you enabled in the configuration in pppwn buildroot. And thank you for this project it's really helpful for me.

**Comment by 0x1iii1ii** [comment]
I think it's unnecessary since the current RAM on Mini B and Plus works just fine with a few tries. Also, I already tried to increase it with NAND Flash memory, but it won't work... if you do know, share it with me I'll test it to see if it actually performs the jailbreak better and is worth investing time in.

**Comment by lakshmihon29** [comment]
I have luckfox pico pro, it has 128mb of ram, but in your build was utilizing only 60mb of ram. I thought by increasing the ram I could increase the stability. I managed to increase ram to 128mb by following the guide on luckfox wiki, I installed pppwn-luckfox on my build, everything was working except pppoe server. I have enabled rp-pppoe in the configuration but it's not working. If you can provide the configuration I could test it out.

**Comment by lakshmihon29** [comment]
In the wiki it was mentioned that 66mb ram ram is allocated for camera usage by default. It can be released manually if the camera is not used.

**Comment by 0x1iii1ii** [comment]
I just checked, I'll test it out today.

**Comment by 0x1iii1ii** [comment]
> I installed pppwn-luckfox on my build, everything was working except pppoe server. 
you mean the only web server won't work, right? if everything else is working how was the stability of jailbreaking the ps4? same or does it take less tries?

**Comment by lakshmihon29** [comment]
I have tried 3 times, in every attempt it jailbreak under 3 attempts. And can you tell what options to enable in the configuration for pppoe server so I can try it with web interface

**Comment by 0x1iii1ii** [comment]
I just updated in [release](https://github.com/0x1iii1ii/PPPwn-Luckfox/releases) page. you can try it and let me know, I tested mine with Pico Plus, and I don't see any significant improvement from the original image. but I think it's still good to have more ram free space.

**Comment by lakshmihon29** [comment]
Thank you so much, I ll check it out. It'll be really helpful if can provide the config file I'd like to tinker around.

**Comment by LouisGarry** [comment]
> I have luckfox pico pro, it has 128mb of ram, but in your build was utilizing only 60mb of ram. I thought by increasing the ram I could increase the stability. I managed to increase ram to 128mb by following the guide on luckfox wiki, I installed pppwn-luckfox on my build, everything was working except pppoe server. I have enabled rp-pppoe in the configuration but it's not working. If you can provide the configuration I could test it out.

Sorry, did you mean "--buffer-size"?   If true, for 128MB what value should be entered?  Thank You
