### ISSUE TITLE
09.00 Payloads

### ISSUE THREAD

**Issue by nomaikk** [0x1iii1ii/PPPwn-Luckfox#53]
Can you add 9.00 payloads, please?
Thanks

**Comment by darkuser89** [comment]
why don't you update to 11.00??

**Comment by nomaikk** [comment]
9.00 works perfectly and is more stable. It has almost no kp. Also, at this moment, there is no game that does not work on 9.00. When the situation changes, which I don't see in the near future, then I will upgrade to 11.00.

**Comment by 0x1iii1ii** [comment]
Added, @nomaikk please test if it works and let me know.

**Comment by nomaikk** [comment]
Thank you very much for the 9.00 payloads. I have tested it and so far without any problems, although it would be great to add the fan control payload.
Thank you again and awaiting more news about this project. For me it's better tan the solution with ESP32.

**Comment by 0x1iii1ii** [comment]
fixed temp control, can you test it?

**Comment by nomaikk** [comment]
Tested and it works like a charm. Thank you very much again.
