### ISSUE TITLE
Support 10.50

### ISSUE THREAD

**Issue by hmcezar** [0x1iii1ii/PPPwn-Luckfox#57]
This is a request, but if someone can guide me through how to do it, I can submit a PR.

Is it possible to support 10.50?
Apparently, @harsha-0110 has done it in his branch.

**Comment by darkuser89** [comment]
why don't you update to 11.00??

**Comment by 0x1iii1ii** [comment]
> This is a request, but if someone can guide me through how to do it, I can submit a PR.
> 
> Is it possible to support 10.50? Apparently, @harsha-0110 has done it in his branch.

please wait on GoldHEN for 10.50 support, this project will only support GoldHEN-compatible FW.
