### ISSUE TITLE
Possible to keep Luckfox on after PPPwn with script stopped???

### ISSUE THREAD

**Issue by ItsJokerZz** [0x1iii1ii/PPPwn-Luckfox#59]
I'd like to keep the Mini B on after running but suspend/stop running the script, rather than shutting it down...

I'm trying to have it plugged into my PC, jailbreak and stop running the script so I can connect my console
via ethernet, as with having it soldered to the board, it wont be able to connect to ethernet via the port...
while on. I am trying to also use the Luckfox for a UART via the GPIO headers. Could we get an option for this?

... Or could someone kindly point my in the right direction to do so, thank you and keep up the great work!

EDIT: If not possible, I'd perfer not to, but could you help with running the script manually if possible, since I have 
to SSH to the Luckfox for the UART anyways but I'd perfer to auto jailbreak, stop the script and stay on and ready.

**Comment by 0x1iii1ii** [comment]
I really don't get your question, but with current features, you can run it manually from the web, you just need to configure it by untick the auto-run PPPwn option.

**Comment by ItsJokerZz** [comment]
Basically, my question is can you add a feature, for the process for PPPwn stops trying to jailbreak the console once done.
It currently will keep running if not set to shutdown after jailbreaking... I do not wana the Luckfox to shutdown, but I dont...
want the script to keep running... if it is, my console CANNOT connect via ethernet since the script is running.

I have the Luckfox soldered to the consoles ethernet, and cannot use ethernet from my router for instance while PPPwn is running,

**Comment by harsha-0110** [comment]
I get your problem. But pppwn stops after the execution and you won't be able to connect to internet via Ethernet because luckfox will be occupying the ethernet port. I have a work around, you can modify the shutdown button to turn off the eth0 of the luckfox so that it won't interfere with Ethernet cable to connect with internet and you can ssh using type c port or uart.

**Comment by harsha-0110** [comment]
If you wanna change shutdown button to turn off eth0 replace the following code in `exec.sh`.
```
killall pppoe-server
sleep 1
awk -v OFS=: '{gsub("\"shutdown_flag\": true", "\"shutdown_flag\": false")}1' "$CONFIG_FILE" >/tmp/tmp.$$.json && mv /tmp/tmp.$$.json "$CONFIG_FILE"
chmod 777 "$CONFIG_FILE"
sleep 1
halt
```
to
```
awk -v OFS=: '{gsub("\"shutdown_flag\": true", "\"shutdown_flag\": false")}1' "$CONFIG_FILE" >/tmp/tmp.$$.json && mv /tmp/tmp.$$.json "$CONFIG_FILE"
chmod 777 "$CONFIG_FILE"
sleep 1
ifconfig eth0 down
```

**Comment by andrea-ap** [comment]
> killall pppoe-server
> sleep 1
Just delete the first two lines of code, delete halt, and add ifconfig eth0 down ?

**Comment by ItsJokerZz** [comment]
I just replaced the line ...
`halt` with `ifconfig eth0 down`
and am trying now...

**Comment by ItsJokerZz** [comment]
I also cannot use `stty` for UART because running 
`ls /dev/ttyS*` returns...
`ls: /dev/ttyS*: No such file or directory`
but the Luckfox Mini B does support.

https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-UART#2-serial-port-testing-shell

**Comment by 0x1iii1ii** [comment]
added to the latest commits https://github.com/0x1iii1ii/PPPwn-Luckfox/commit/b194d28fe0b7385c1fb30dd00e601f0ff6c1a908

**Comment by ItsJokerZz** [comment]
Worked and can connect to via ethernet now, but the GPIO UART headers are unavailable, as mentioned in the previous message.
