### ISSUE TITLE
Reinstallation PPPwn-Luckfox-v1.2.2.zip 

### ISSUE THREAD

**Issue by andrea-ap** [0x1iii1ii/PPPwn-Luckfox#61]
But if I download when there is an update PPPwn-Luckfox-v1.2.2.zip, can I reload it in ssh in Luckfox Pico Pro with MobaXterm, or do I have to redo the procedure from scratch with flash etc.....

**Comment by 0x1iii1ii** [comment]
do a clean install from scratch is always recommended!

**Comment by jonnibravo** [comment]
Just 

> But if I download when there is an update PPPwn-Luckfox-v1.2.2.zip, can I reload it in ssh in Luckfox Pico Pro with MobaXterm, or do I have to redo the procedure from scratch with flash etc.....

Just open luckfox in mobaxterm, delete the previously installed pppwn folder and copy the new pppwn folder, reinstall the new pppwn folder

**Comment by jonnibravo** [comment]
> do a clean install from scratch is always recommended!

Sorry you are right, I did just that(fresh install) and it works perfectly now and my ps4 shuts down normally, at least for the moment.
