### ISSUE TITLE
About Web Server

### ISSUE THREAD

**Issue by LouisGarry** [0x1iii1ii/PPPwn-Luckfox#62]
Hello master, Web Server can only be accessed after PPPwned?  Is it possible to access before PPPwned?

Thanks

**Comment by 0x1iii1ii** [comment]
just config PPPwn to not run at start up. thus when you boot ps4 the web server should be running.

**Comment by LouisGarry** [comment]
> just config PPPwn to not run at start up. thus when you boot ps4 the web server should be running.

What if it turns out that we chose the wrong PPPwn in the config and it keeps failing, does that mean we have to reflash it again?
