### ISSUE TITLE
What is correct command for 1.0.2?

### ISSUE THREAD

**Issue by IRONB0SS** [0x1iii1ii/PPPwn-Luckfox#65]
This didn't work

cd PPPwn-Luckfox
chmod +x install.sh
./install.sh

**Comment by 0x1iii1ii** [comment]
> cd PPPwn-Luckfox chmod +x install.sh ./install.sh

this cmd should work on 1.0.2, maybe try to check your dir PPPwn-Luckfox name. Also, why don't you use the latest release?

**Comment by IRONB0SS** [comment]
![IMG_20240821_121511_945.jpg](https://github.com/user-attachments/assets/2b82650b-8d0f-47e9-8996-9329cf43a8ed)

**Comment by IRONB0SS** [comment]
Do you recommend sd or nand?

**Comment by IRONB0SS** [comment]
Try one; after 4 mins PS4 got hang

![Screenshot_20240821_125213_Clock.jpg](https://github.com/user-attachments/assets/5146d54c-932d-4fee-b8f6-8297b11ff623)

**Comment by harsha-0110** [comment]
> Do you recommend sd or nand?

I recommend NAND cause it's cheaper, boots faster.
