### ISSUE TITLE
Not a problem but a noob question: FTP server.

### ISSUE THREAD

**Issue by merdellin** [0x1iii1ii/PPPwn-Luckfox#67]
Not a problem but a noob question: FTP server.
After launching the payload from the webserver, how do I connect to the PS4 from my PC?
Thanks in advance for your patience.

**Comment by 0x1iii1ii** [comment]
Connect your PS4 WiFi to your computer network (connect both to the same WiFi network), and use your PS4 IP address to access FTP via FileZilla.
