### ISSUE TITLE
Ethernet Pinout

### ISSUE THREAD

**Issue by Jstzo2u** [0x1iii1ii/PPPwn-Luckfox#7]
I am using LuckFox Pico, Ethernet Pinout. However, after inserting it into the router, the router does not recognize it. How can I solve this problem.

**Comment by Jstzo2u** [comment]
Solved, the system is using Luckfox-Pico-Plus_Ubuntu SDCard, and pin 4578 needs to be connected to GND.

**Comment by Jstzo2u** [comment]
**PS4 System 10.01**
**LuckFox Pico**
**Approximately 6-8 cycles, successful**
![1](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/131769500/21479cca-226e-437f-a349-88b4016978c8)
![2](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/131769500/edf62733-7bdd-4194-9ebc-ba399d39a63e)
![3](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/131769500/9d71a55f-cd63-49f1-9730-d48a58bf8a35)

**Comment by 0x1iii1ii** [comment]
there's a nice ethernet connection you got there, thanks for the test on 10.01

**Comment by Jstzo2u** [comment]
> there's a nice ethernet connection you got there, thanks for the test on 10.01

You are welcome.

**Comment by Jstzo2u** [comment]
> there's a nice ethernet connection you got there, thanks for the test on 10.01

![1](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/131769500/21caf6e9-7694-454b-a54b-86a111adb3da)
![2](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/131769500/32e19124-78e8-4f8f-a744-fb073d14b8a9)
9.60 is work!

**Comment by darthtrader6502** [comment]
> I am using LuckFox Pico, Ethernet Pinout. However, after inserting it into the router, the router does not recognize it. How can I solve this problem.

Hi mate...how can i contact u if have any question regarding this luckfox pico?

**Comment by darthtrader6502** [comment]
> Solved, the system is using Luckfox-Pico-Plus_Ubuntu SDCard, and pin 4578 needs to be connected to GND.

need help...what if i dont have a router...how to solve this to finish the setup..thanks

**Comment by darthtrader6502** [comment]
> I am using LuckFox Pico, Ethernet Pinout. However, after inserting it into the router, the router does not recognize it. How can I solve this problem.

must use the router? is there any other way to get the ip?

**Comment by 0x1iii1ii** [comment]
Connect it directly to your PC assign custom IP, Subnet Mask, Gateway, and try again.

**Comment by Jstzo2u** [comment]
> > I am using LuckFox Pico, Ethernet Pinout. However, after inserting it into the router, the router does not recognize it. How can I solve this problem.
> 
> must use the router? is there any other way to get the ip?

https://wiki.luckfox.com/Luckfox-Pico/Luckfox-Pico-Login-ADB/
I hope it will be helpful to you

**Comment by Jstzo2u** [comment]
> Connect it directly to your PC assign custom IP, Subnet Mask, Gateway, and try again.

Hi，Do you know how to export images from SPI NAND FLASH? Convenient to write img firmware into Nand Flash of other Lukcbox.
Backup export instead of uBuntu compiling *. img
As shown in the figure (write):

![1](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/131769500/215cc716-9c87-4ec2-a3a3-78b7578174b5)

I want to export the firmware written on the image from the Nand Flash backup

**Comment by darthtrader6502** [comment]
Hi...thanks guys for your help...especially @0x1iii1ii . Successfully jailbreak but am i doing it right? feels like it can be better...please help comment...
thanks to @Jstzo2u also...i did connect the eth pin like u did...
by the way this is how i did it...
1.i am using MobaXterm.
2.No router.
3.only laptop with ethernet slot ready
4.both luckfox power and eth cable connect to the laptop.
5.edit the Configure a static IP for the RNDIS network (luckfox tutorial)
6.use the static ip 172.32.0.70 
7.patient
8.at the end there is error failed to load Daemon? is it ok? is it really error or suppose to be like that?
thanks guys...
![WhatsApp Image 2024-06-16 at 21 51 02_4c0c72b9](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/171436333/aae88d02-1682-491f-a5a5-fa3c0ec4539b)
![WhatsApp Image 2024-06-16 at 21 46 28_e02dcf81](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/171436333/6d281390-0ab0-4ece-8602-b585c2907eb7)
![WhatsApp Image 2024-06-16 at 21 57 03_5b899727](https://github.com/0x1iii1ii/PPPwn-Luckfox/assets/171436333/08e38b02-4c7f-4c09-aea7-cd9039c8109f)
