### ISSUE TITLE
disable pppwn on start

### ISSUE THREAD

**Issue by biilyz** [0x1iii1ii/PPPwn-Luckfox#70]
Can you set pppwn to off by default after flashing luckfox?
Many times I choose pppwnv6 mode for ps4 pro and it crashes, so when I plug luckfox in, it keeps running pppwn and crashes, unable to access the php web to reconfigure.

**Comment by 0x1iii1ii** [comment]
it does make sense, I changed it to off in the latest commit, download zip from repo and test it.

**Comment by 0x1iii1ii** [comment]
you can also change it to pppwn by doing a fresh install again.

**Comment by biilyz** [comment]
> you can also change it to pppwn by doing a fresh install again.


Thank you for the fix
There's  still a problem: when I click "run pppwn" on the php page, unfortunately my ps4 has KP, when I reboot it continues to run pppwn (I haven't enabled  auto run PPPwn on startup ). Can you also turn it off?

**Comment by 0x1iii1ii** [comment]
go to `/etc/pppwn/config.json` and change` "AUTO_START": false,`
