### ISSUE TITLE
kernel panic when luckyfox try to re-activate hen already active

### ISSUE THREAD

**Issue by Israsdt** [0x1iii1ii/PPPwn-Luckfox#73]
I have a problem, I have the USB ports that do not give power when the console goes into hibernation mode, when reactivating the console from hibernation mode, luckfox starts again and tries to activate goldhen again, as goldhen is still active what it does is jump a kernelpanic when the console is turned off, could not something be done so that luckfox checks that goldhen is enabled and does not launch it automatically again? thanks

**Comment by ps4rokx** [comment]
KP is common problem of luckfox. Sudden shutdown when restart or PS4 switch off.. so gone back to esp32s2 mod for my 9.0.

**Comment by 0x1iii1ii** [comment]
> I have a problem, I have the USB ports that do not give power when the console goes into hibernation mode, when reactivating the console from hibernation mode, luckfox starts again and tries to activate goldhen again, as goldhen is still active what it does is jump a kernelpanic when the console is turned off, could not something be done so that luckfox checks that goldhen is enabled and does not launch it automatically again? thanks

Currently, there is no feature to detect ps4 in rest mode, what you can do now is go to the home screen and select `Settings > System, Select Power Saving > Features Available in Rest Mode.`
Set the supply power to USB ports to **_always_**.
