### ISSUE TITLE
In version 1.2.3, 10.50, 10.70, or 10.71 cannot be selected

### ISSUE THREAD

**Issue by CHENGSHANGFA** [0x1iii1ii/PPPwn-Luckfox#77]
Hi, have a nice day!
Glad to see you updated the new version！
I updated my Luckfox Pico Plus and found that the PS4 firmware version catalog does not have 10.50, 10.70, 10.71 options.

**Comment by CHENGSHANGFA** [comment]
![1725938226755](https://github.com/user-attachments/assets/ecf8e50d-6681-4752-8ee8-b05cb7dc63cb)

**Comment by 0x1iii1ii** [comment]
Will be added when the new version of GoldHEN is released! even if i added those version it's pointless since we don't have GoldHEN support that FW.

**Comment by CHENGSHANGFA** [comment]
Okay, thank you
