### ISSUE TITLE
luckfox 1.2.3 not works

### ISSUE THREAD

**Issue by ciss84** [0x1iii1ii/PPPwn-Luckfox#82]
1.2.3 not works on my luckfox  not load jb !! 1.2.2 works fine

**Comment by Banex3010** [comment]
Replace rush.sh from 1.2.2 with 1.2.3
but it crash every single time

**Comment by ciss84** [comment]
thx im use full 1.2.2 for moment

**Comment by ciss84** [comment]
after several tries of 1.2.3 have replace in run.sh

if [ "$AUTO_START" = "true" ]; then
  /etc/init.d/S50nginx stop
  /etc/init.d/S49php-fpm stop
  > $LOG_FILE
  sleep 1
  reseteth
  $CMD >> $LOG_FILE 2>&1
  if grep -q "\[+\] Done!" $LOG_FILE; then
    echo "PPPwned"
    if [ "$HALT_CHOICE" = "true" ]; then
      sleep 1
      halt
    else
      reseteth
      pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 192.168.1.1 -R 192.168.1.2 &
      sleep 5
      /etc/init.d/S50nginx start
      /etc/init.d/S49php-fpm start
    fi
  fi

to this 

if [ "$AUTO_START" = "true" ]; then
  /etc/init.d/S50nginx stop
  /etc/init.d/S49php-fpm stop
  > $LOG_FILE
  sleep 1
  reseteth
  $CMD
  echo "PPPwned"
    if [ "$HALT_CHOICE" = "true" ]; then
      sleep 1
      halt
    else
      reseteth
      pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 192.168.1.1 -R 192.168.1.2 &
      sleep 5
      /etc/init.d/S50nginx start
      /etc/init.d/S49php-fpm start
  fi

and have replace in web-run.sh

killall nginx
killall php-fpm
killall pppoe-server
> $LOG_FILE
sleep 1
reseteth
$CMD >> $LOG_FILE 2>&1
if grep -q "\[+\] Done!" $LOG_FILE; then
    sleep 5
    reseteth
    pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 192.168.1.1 -R 192.168.1.2 &
    sleep 5
    /etc/init.d/S50nginx start
    /etc/init.d/S49php-fpm start
fi

to this 

killall nginx
killall php-fpm
killall pppoe-server
> $LOG_FILE
sleep 1
reseteth
$CMD
pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 192.168.1.1 -R 192.168.1.2 &
sleep 5
/etc/init.d/S50nginx start
/etc/init.d/S49php-fpm start

and works perfectly

**Comment by jason-eu** [comment]
> after several tries of 1.2.3 have replace in run.sh
> 
> if [ "$AUTO_START" = "true" ]; then /etc/init.d/S50nginx stop /etc/init.d/S49php-fpm stop
> 
> > $LOG_FILE
> > sleep 1
> > reseteth
> > $CMD >> $LOG_FILE 2>&1
> > if grep -q "[+] Done!" $LOG_FILE; then
> > echo "PPPwned"
> > if [ "$HALT_CHOICE" = "true" ]; then
> > sleep 1
> > halt
> > else
> > reseteth
> > pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 192.168.1.1 -R 192.168.1.2 &
> > sleep 5
> > /etc/init.d/S50nginx start
> > /etc/init.d/S49php-fpm start
> > fi
> > fi
> 
> to this
> 
> if [ "$AUTO_START" = "true" ]; then /etc/init.d/S50nginx stop /etc/init.d/S49php-fpm stop
> 
> > $LOG_FILE
> > sleep 1
> > reseteth
> > $CMD
> > echo "PPPwned"
> > if [ "$HALT_CHOICE" = "true" ]; then
> > sleep 1
> > halt
> > else
> > reseteth
> > pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 192.168.1.1 -R 192.168.1.2 &
> > sleep 5
> > /etc/init.d/S50nginx start
> > /etc/init.d/S49php-fpm start
> > fi
> 
> and have replace in web-run.sh
> 
> killall nginx killall php-fpm killall pppoe-server
> 
> > $LOG_FILE
> > sleep 1
> > reseteth
> > $CMD >> $LOG_FILE 2>&1
> > if grep -q "[+] Done!" $LOG_FILE; then
> > sleep 5
> > reseteth
> > pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 192.168.1.1 -R 192.168.1.2 &
> > sleep 5
> > /etc/init.d/S50nginx start
> > /etc/init.d/S49php-fpm start
> > fi
> 
> to this
> 
> killall nginx killall php-fpm killall pppoe-server
> 
> > $LOG_FILE
> > sleep 1
> > reseteth
> > $CMD
> > pppoe-server -I eth0 -T 60 -N 1 -C isp -S isp -L 192.168.1.1 -R 192.168.1.2 &
> > sleep 5
> > /etc/init.d/S50nginx start
> > /etc/init.d/S49php-fpm start
> 
> and works perfectly

@0x1iii1ii 
Did you try this to help with stability?

**Comment by Nanganator** [comment]
Just delete /etc/pppwn/config.json then run /root/PPPwn-Luckfox/install.sh again.
