### ISSUE TITLE
Ps4 Slim 2216A

### ISSUE THREAD

**Issue by Banex3010** [0x1iii1ii/PPPwn-Luckfox#87]
Hi
pico luck fox at any version crashes ps4 2216A 500GB 
i changed HDD to fresh one crashed
i changed pico's all versions crashed again
i used 5 different pico luck fox's but crashes again
zero luck
but it's  working with pppwn Loader on pc fine 
what can be the problem ?

**Comment by ps4rokx** [comment]
> Hi pico luck fox at any version crashes ps4 2216A 500GB i changed HDD to fresh one crashed i changed pico's all versions crashed again i used 5 different pico luck fox's but crashes again zero luck but it's working with pppwn Loader on pc fine what can be the problem ?

If u r using luckfox then there is no luck.. luckfox main problem is crush, whatever it's going on to jb or restart or shutdown...

**Comment by Banex3010** [comment]
> > Hi pico luck fox at any version crashes ps4 2216A 500GB i changed HDD to fresh one crashed i changed pico's all versions crashed again i used 5 different pico luck fox's but crashes again zero luck but it's working with pppwn Loader on pc fine what can be the problem ?
> 
> If u r using luckfox then there is no luck.. luckfox main problem is crush, whatever it's going on to jb or restart or shutdown...

on 2216A or else ??

**Comment by Banex3010** [comment]
well
in installation use (IPV6) option FIXED the problem
