### ISSUE TITLE
i never updated my luckfox since 1.1.0 what i do to update

### ISSUE THREAD

**Issue by narhamraatallah** [0x1iii1ii/PPPwn-Luckfox#89]
i never updated my luckfox since 1.1.0 what i do to update

do i need to load the image again luckfox_pico_plus_image_minimal_NAND.zip
 or just replace the folder PPPwn-Luckfox-v1.1.1.zip
 
 ps: i do not remember if my luckfox is plus or pro or max , is there a way to know??

**Comment by jason-eu** [comment]
close this issue
