### ISSUE TITLE
re-activation check

### ISSUE THREAD

**Issue by Bolgar01** [0x1iii1ii/PPPwn-Luckfox#94]
Hello my friend. First of all, thank you for your hard work. secondly, I, like many others, am tormented by this problem. luckfox, when exiting rest mode, does not see the running activation and a kernel panic occurs. For example, in PI-Pwn there are lines that check for the presence of running pppwn. Please, add this feature to your scripts. This is important when using luckfox mini for embedding inside consoles. Thank you

https://github.com/0x1iii1ii/PPPwn-Luckfox/issues/73

What you advise here doesn't work. USB power goes out temporarily every time the console goes to sleep, then comes back again

https://github.com/stooged/PI-Pwn/blob/main/PPPwn/run.sh

**Comment by Bolgar01** [comment]
https://github.com/0x1iii1ii/PPPwn-Luckfox/issues/73

What you advise here doesn't work. USB power goes out temporarily every time the console goes to sleep, then comes back again

**Comment by 0x1iii1ii** [comment]
you can expect it in the next version.

**Comment by 0x1iii1ii** [comment]
added to the latest version https://github.com/0x1iii1ii/PPPwn-Luckfox/releases/tag/1.2.5
