### ISSUE TITLE
Can't ssh into Luckfox Pico Pro/Max RV1106

### ISSUE THREAD

**Issue by atsetilam** [0x1iii1ii/PPPwn-Luckfox#95]
I followed all the steps until launching MobaXterm but I can't ssh into my Luckfox Pico-M-256MB. It will timeout without prompting me for user and password. The IP I'm trying to ssh into is 172.32.0.93 as stated in the guide.
It does get recognized by my Windows machine and I can set the static IP on it (172.32.0.100). 

I tried to ssh from a different computer (Macbook Pro) and still fails.

The device blinks every 1 second (I think?).

Any help?

**Comment by 0x1iii1ii** [comment]
try to follow the tutorial on YouTube, with less info I can't help solve the problem.

**Comment by 0x1iii1ii** [comment]
please use the latest pre-installed build https://github.com/0x1iii1ii/PPPwn-Luckfox/releases/tag/1.2.5
