### ISSUE TITLE
Cannot find Remote NDIS based Internet Sharing Device in my Network and Sharing center

### ISSUE THREAD

**Issue by suboticki** [0x1iii1ii/PPPwn-Luckfox#96]
My luckfox pico plus is not showing up when I enter my Network and Sharing center.

I tried 2 different computers, switching cables, turning off Windows Firewall, plugging luckfox via ethernet cable to computer, reinstalling flash firmware and nothing. I tried checking Device Manager and scanning for hardware changes in Network Adapters and luckfox still isn't detected as a ethernet.
Both computers I tried using are laptops, one is running Windows 10, and the other one is running Windows 11. Same problem on both.

Luckfox Pico connects as it is supposed when i turn on the Soc ToolKit.

Does anybody have an Idea how I could fix this?

**Comment by 0x1iii1ii** [comment]
Make sure your USB type-c cable is original and genius.

**Comment by suboticki** [comment]
The problem was with the power button on the luckfox pico. I fixed it by spamming the button while turning it on, and that worked for some reason.

**Comment by suboticki** [comment]
The problem was with the power button on the luckfox pico. I fixed it by spamming the button while turning it on, and that worked for some reason.
