### ISSUE TITLE
config.json not updating when installing 1.2.3 over top of 1.2.2

### ISSUE THREAD

**Issue by Nanganator** [0x1iii1ii/PPPwn-Luckfox#97]
Issue is described in #82 

When installing 1.2.3 over the top of an existing 1.2.2 install, the section below to update the config.json file in /etc/pppwn does not work (because the config.json already exists). Meaning the old 1.2.2 config.json remains and does not have the log_file variable defined. The JB just then goes into a loop (if auto retry is set).

```
# Create the config.json file with the install directory if it doesn't exist
if [ ! -f "$CONFIG_FILE" ]; then
    cat >$CONFIG_FILE mv confi	<<EOL
{
    "FW_VERSION": "$FW_VERSION",
    "TIMEOUT": "5",
    "WAIT_AFTER_PIN": "5",
    "GROOM_DELAY": "4",
    "BUFFER_SIZE": "0",
    "AUTO_RETRY": true,
    "NO_WAIT_PADI": false,
    "REAL_SLEEP": false,
    "AUTO_START": true,
	"HALT_CHOICE": $HALT_CHOICE,
	"PPPWN_EXEC": "$PPPWN_EXEC",
    "install_dir": "$CURRENT_DIR",
    "log_file": "$LOG_DIR",
    "shutdown_flag": false,
    "execute_flag": false,
    "eth0_flag": false
}
EOL
    chmod 777 $CONFIG_FILE
```

As a workaround you can simply rename/remove the existing /etc/pppwn/config.json, navigate back to /root/PPPwn-Luckfox and run the install.sh again. This generates a new config.json which has the log_file variable defined.

I think the point is though that you shouldn't even have this issue as you’re supposed to fully reflash the buildroot which wipes out all previous files.

**Comment by 0x1iii1ii** [comment]
Thank you for your report, it will be fixed in the next version.

**Comment by 0x1iii1ii** [comment]
fixed, but I'd recommend using the pre-build image.
