### ISSUE TITLE
GoldHEN 2.4b18 has been released

### ISSUE THREAD

**Issue by jason-eu** [0x1iii1ii/PPPwn-Luckfox#98]
https://x.com/Kameleonre_/status/1850768786833490260

**Comment by branchus** [comment]
I think the latest version already updated with latest stage 2. only thing you need to do is to put the new goldhen on a usb and jailbreak using this PPPWn-luckfox. the new goldhen will be copied to PS4 internal hard disk and used.

by the way, I have already updated the goldhen using above.

**Comment by krakenbites** [comment]
Unfortunately we will need @0x1iii1ii to step in and update PPPwn Luckfox because 10.50, 10.70 and 10.71 aren't showing on the Mobaxterm console. I'm on 10.50 and therefore I can't jailbreak as of now.

![image](https://github.com/user-attachments/assets/70574a4f-21f6-470b-abdd-a6dc6b668240)

@0x1iii1ii can you please update?

**Comment by 0x1iii1ii** [comment]
Added https://github.com/0x1iii1ii/PPPwn-Luckfox/releases/tag/1.2.4_1.1.2

**Comment by jason-eu** [comment]
> Added https://github.com/0x1iii1ii/PPPwn-Luckfox/releases/tag/1.2.4_1.1.2

Thank you @0x1iii1ii 😊

**Comment by branchus** [comment]
tried 1.1.2, to me at least, a lot less stable than 1.1.1

first test - took super long to jailbreak, had kernel panic and reboot automatically into disk check.
second test - jailbroke within 5 retries. but a bad shutdown. power cycle into disk check...

using goldhen 2.4b18

I will go back to 1.1.1

**Comment by 0x1iii1ii** [comment]
maybe you can try 1.2.4, or keep using 1.1.1, its very depend on ps4, mine on 1.1.2 work fine here!

**Comment by krakenbites** [comment]
> maybe you can try 1.2.4, or keep using 1.1.1, its very depend on ps4, mine on 1.1.2 work fine here!

I'm on 10.50, is it possible for me to try these older releases and test if they are more stable for my PS4 Pro? Thanks!
