### ISSUE TITLE
PPPwn-Luckfox Version

### ISSUE THREAD

**Issue by AMGe350** [0x1iii1ii/PPPwn-Luckfox#99]
Dear Genius,

I would like to first commend you on a fantastic bit of coding that makes a HUGE amount of difference in MANY individuals lives.

Would it be possible please to submit, one minor request?

Would it be possible to somehow code the PS4 webserver screen 
with the version number of which Luckfox coding is being utilised please?
Example:
1. Jailbreak PS4 as usual.
2. Access & open the Internet Explorer.
3. Type in 192.168.1.1
4. On this screen it would be greatly appreciated if the Luckfox version could somehow appear.

Many thanks & any questions, please dont hesitate in contacting me.

**Comment by jason-eu** [comment]
How would you expect that to work?

**Comment by AMGe350** [comment]
My friend, your a coding GENIUS!! Two stars with the version number in-between.......it looks beautiful.......THANKYOU
